#!/usr/bin/env sh

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

commit_message="$(cat $1 | head -n1)"
commit_format="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\!?(\((.*?)\))?\!?: (.*?)$"
convention_docs='https://tokopedia.atlassian.net/wiki/spaces/PINFRA/pages/2020868902/Convention+for+Naming+Branches+and+Commits'


# ignore merge branch
if echo "$commit_message" | grep -qE "^Merge branch \'"; then
	exit 0
fi

# check semantic scheme
if ! echo "$commit_message" | grep -qE "${commit_format}"; then
	printf "Your commit message didn't follow the convention: ${YELLOW}$commit_message${NC}

Correct example: ${GREEN}feat(core): add awesome feature${NC}

Please refer to: ${BLUE}\e[4m${convention_docs}"; echo
	exit 1
fi