name: "PR Lint"

on:
  pull_request_target:
    types:
      - edited
      - opened
      - synchronize

jobs:
  validate:
    name: Validate title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed.
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
          # Configure that a scope must always be provided.
          requireScope: false
            
